# Generated by Django 4.2.7 on 2024-12-20 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("csv_file", models.FileField(upload_to="project_files/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "regression_type",
                    models.CharField(
                        choices=[
                            ("OLS", "Ordinary Least Squares"),
                            ("2SLS", "Two-Stage Least Squares"),
                            ("LOGIT", "Logistic Regression"),
                        ],
                        default="OLS",
                        max_length=10,
                    ),
                ),
                (
                    "x_variables",
                    models.JSONField(help_text="List of independent variables"),
                ),
                (
                    "y_variable",
                    models.CharField(help_text="Dependent variable", max_length=100),
                ),
                (
                    "control_variables",
                    models.JSONField(
                        blank=True, help_text="List of control variables", null=True
                    ),
                ),
                (
                    "heterogeneous_variables",
                    models.JSONField(
                        blank=True,
                        help_text="List of heterogeneous variables",
                        null=True,
                    ),
                ),
                (
                    "mediating_variables",
                    models.JSONField(
                        blank=True, help_text="List of mediating variables", null=True
                    ),
                ),
                (
                    "results",
                    models.JSONField(
                        blank=True, help_text="Regression results", null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
