# Generated by Django 4.2.7 on 2024-12-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("regression_project", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="control_variables",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of control variables",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="heterogeneous_variables",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of heterogeneous variables",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="mediating_variables",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of mediating variables",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="regression_type",
            field=models.CharField(
                choices=[
                    ("PANEL", "Panel Data Analysis"),
                    ("DID", "Difference in Differences"),
                ],
                default="OLS",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="x_variables",
            field=models.JSONField(
                default=list, help_text="List of independent variables"
            ),
        ),
    ]
